[package]
name = "fat32-parser"
version = "0.1.0"
edition = "2021"
authors = ["Franklin"]
description = "Parser FAT32 pour environnement no_std"

[dependencies]

[dev-dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
